// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg0M_c5FBaklzoshR4FEes2FgO-IIdfKs',
    appId: '1:617400207971:web:e5a08144e122ecb6d58656',
    messagingSenderId: '617400207971',
    projectId: 'mera-mann-6394c',
    authDomain: 'mera-mann-6394c.firebaseapp.com',
    storageBucket: 'mera-mann-6394c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR3P_2HLD1sQBLOwfbvvbpAhoZAdhl-lU',
    appId: '1:617400207971:android:166a3c693adce6bad58656',
    messagingSenderId: '617400207971',
    projectId: 'mera-mann-6394c',
    storageBucket: 'mera-mann-6394c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2nQG5rOgQEzRyrIDsju0GR7aDRKT-Efs',
    appId: '1:617400207971:ios:5017f59f486b51bcd58656',
    messagingSenderId: '617400207971',
    projectId: 'mera-mann-6394c',
    storageBucket: 'mera-mann-6394c.appspot.com',
    iosClientId: '617400207971-rqvsf5ftiqig3ebufg0pv1m4k244a9qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.meraMann',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2nQG5rOgQEzRyrIDsju0GR7aDRKT-Efs',
    appId: '1:617400207971:ios:5017f59f486b51bcd58656',
    messagingSenderId: '617400207971',
    projectId: 'mera-mann-6394c',
    storageBucket: 'mera-mann-6394c.appspot.com',
    iosClientId: '617400207971-rqvsf5ftiqig3ebufg0pv1m4k244a9qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.meraMann',
  );
}
